### ISSUE TITLE
Support for foodcritic

### ISSUE THREAD

**Issue by mhedgpeth** [pendrica/vscode-chef#5]
I see that there is support for Rubocop but not foodcritic. Would it be easy to support foodcritic as well?

**Comment by stuartpreston** [comment]
Certainly possible...  The reason I haven't done anything with it at the moment is that I need to know the names of the cookbooks under test, where many people using the tool point at a complete repo containing many cookbooks.  The question is how to determine the name of the cookbook we want to run food critic against. All thoughts appreciated.

**Comment by mhedgpeth** [comment]
Could you iterate through all folders, looking for a metadata.rb containing a name 'cookbook_name' text where the cookbook_name matched the folder, and run foodcritic inside of that folder?

I wonder if that would be performant as well...

**Comment by smith** [comment]
The `name` attribute has been required in metadata.rb for a long time, so I think reading that from the root of the cookbook would be the most reliable approach.

**Comment by stuartpreston** [comment]
So maybe I didn't phrase my question precisely.  I can get the name of the cookbooks, but in the "one big repo" sense I'm still concerned with how to determine which specific cookbook you want to run foodcritic automatically against. What are people's thoughts on that?

**Comment by mhedgpeth** [comment]
I suggest doing it for all cookbooks that are found in the tree.

**Comment by stuartpreston** [comment]
I've added some experimental support in the latest version (0.5.1) that is now published to the gallery. I chose not to enable Foodcritic support globally because of the performance I saw (e.g. Foodcritic takes ~25 seconds to execute against the Apache2 cookbook).

To enable it, you'll need to go to your user/workspace settings and add the following setting:

```"foodcritic.enable": true```

Please give it a go and let me know how you get on.

**Comment by mhedgpeth** [comment]
Actually for me my window is freezing when I opened my large project, even when I turned the setting back off. Is there a log I could use to investigate?

**Comment by stuartpreston** [comment]
I'm not aware of one. All the linting happens on a spawned process so shouldn't affect your UI thread.

**Comment by stuartpreston** [comment]
Actually, some stuff to detect the cookbooks has been moved to the activation method, what sort of size of project are we talking?

**Comment by stuartpreston** [comment]
The code to detect the available cookbooks is outside the Foodcritic feature flag. Looks like I'll have to move some stuff around (at a guess)

**Comment by stuartpreston** [comment]
Please retry this against the latest version (0.5.2). I've moved the cookbook detection inside the Foodcritic feature flag, hopefully now it'll only be slow when you enable the feature flag (but this work will happen on a background thread).

**Comment by mhedgpeth** [comment]
That fixed the problems I was having. I wonder if there is a way to just run it on the active files? It seems like a lot of wasted processing to run it on anything other than the active file, since no one is ever going to use that information.

**Comment by stuartpreston** [comment]
I looked at that but Foodcritic only works against entire cookbooks rather than individual files. Also to keep the error/warning/info counts up to date we need to run against all cookbooks across the "workspace" (repo).

**Comment by mhedgpeth** [comment]
Is that because it only runs it on the save? Could you run foodcritic on an
open? The algorithm would be something like this:

For every file in working files (do this whenever that changes) do
  look in the current folder or above for metadata.rb for cookbook name
  in that folder run foodcritic
  map results to all files it says
end

**Comment by stuartpreston** [comment]
Sure, Ignoring the bit where we have to search for metadata.rb or metadata.json for the name -- all the  Foodcritic and Rubocop results are sent to an array containing all the diagnostics for the entire repo.

Because there's no way to de-dupe diagnostics, the array is cleared every time Foodcritic and Rubocop are run.

It would be very confusing to the end user to have the diagnostics count jump up and down based on the working files.  In my opinion the diagnostics counts should be showing results across the entire repo and be a continuously updating thing for the project.

When I get some more time to devote to this I'll see what other options there are.

**Comment by mhedgpeth** [comment]
That makes total sense Stuart. I didn't think about the issue count. Thanks
for giving it a shot; the plugin is fantastic.

**Comment by stuartpreston** [comment]
I'm closing this issue for now, we have experimental support in but probably could chat at ChefConf about how to improve it :)

**Comment by mhedgpeth** [comment]
Absolutely!
